### ISSUE TITLE
HA 경고 메시지

### ISSUE THREAD

**Issue by Murianwind** [oukene/extend_temperature#2]
HA Core 2025.01에 예정된 변경사항에 대한 경고메시지에 대해 업데이트 해주시면 감사하겠습니다.

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: 센서 (documentation, issues)
First occurred: 08:10:44 (10 occurrences)
Last logged: 08:11:06

DEVICE_CLASS_TEMPERATURE was used from extend_temperature, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please report it to the author of the 'extend_temperature' custom integration

**Comment by oukene** [comment]
수정완료

**Comment by Murianwind** [comment]
감사합니다. 새해 복 많이 많이 받으세요!!

**Comment by Murianwind** [comment]
감사합니다.

새해 복 많이 많이 받으세요. ^^

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 1월 5일 (금) 오전 9:23, oukene ***@***.***>님이 작성:
