### ISSUE TITLE
HA Core 5.0 업데이트 이후 센서가 갱신이 되지를 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [oukene/extend_temperature#3]
![image](https://github.com/oukene/extend_temperature/assets/6447460/84660451-f28f-45cd-b37c-4466b2419147)

![image](https://github.com/oukene/extend_temperature/assets/6447460/dabeaf09-8b13-4715-ada2-a715dbc1746b)

기기에서 다시 읽어오기를 해야만 센서가 갱신이 됩니다.

**Comment by oukene** [comment]
수정되었습니다

**Comment by Murianwind** [comment]
> 수정되었습니다

감사합니다 ^^
